modLoader="javafml"

loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="ex_nihilo_random"
version="1.0.0.1"
displayName="Ex Nihilo: Random"
logoFile=""
credits="Ex Nihilo: Random"
authors="Love, goulixiaoji of Abstruck"
description='''
Thank you.
'''

[[dependencies.ex_nihilo_random]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ex_nihilo_random]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ex_nihilo_random]]
    modId="cavesandcliffs"
    mandatory=false
    versionRange="6.2"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ex_nihilo_random]]
    modId="taiga"
    mandatory=false
    versionRange="${file.jarVersion}"
    ordering="AFTER"
    side="BOTH"